# This workflow builds a Docker image and pushes it to Docker Hub on every push to the main branch.

name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code so the workflow can access it.
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using secrets for credentials.
      # This uses the official Docker action which is secure and reliable.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      # Step 3: Build the Docker image and push it to Docker Hub.
      # This action combines the 'docker build' and 'docker push' steps.
      # It automatically tags the image with your Docker Hub username and the repo name.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tags the image with 'latest' and also with the Git commit SHA for versioning.
          # Example: jjuma/nodejs-cicd:latest, jjuma/nodejs-cicd:a1b2c3d
          tags: ${{secrets.DOCKER_USERNAME}}/nodejs-cicd:latest,${{secrets.DOCKER_USERNAME}}/nodejs-cicd:${{ github.sha}}