name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD --password-stdin
      
    - name: Build the Docker image
      run: docker build -t josephjuma24/nodejs-cicd .
    - name: Push to Dockerhub
      run: docker push josephjuma24/nodejs-cicd
